export const keyboardLetters = [
  ['W', 'E', 'É', 'R', 'T', 'U', 'Ú','I', 'Í', 'O', 'Ó', 'P'],
  ['A', 'Á', 'S', 'D', 'F', 'G', 'H', 'L'],
  ['C', 'V', 'B', 'N', 'M'],
]

export const letters = [
  'A',
  'Á',
  'B',
  'C',
  'D',
  'E',
  'É',
  'F',
  'G',
  'H',
  'I',
  'Í',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'Ó',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'Ú',
  'V',
  'W',
  'X',
  'Y',
  'Z',
]

export const status = {
  green: 'green',
  yellow: 'yellow',
  gray: 'gray',
  unguessed: 'unguessed',
}

export const dictionary = {
  HowToPlay: 'Treoireacha',
  SixGuessesLeft: 'Tá 6 thomhas agat leis an fhocal cheart a thomhas.',
  GuessAnyValidWord: 'Glacfar le focail bailí Gaeilge ar bith.',
  AfterEachGuessLetterWillTurnDifferentColour: 'I ndiaidh gach tomhas, cuirfear dath glas, buí nó liath ar na litreacha a chur tú isteach.',
  CorrectLetterCorrectSpot: 'An litir ceart, san áit cheart',
  CorrectLetterWrongSpot: 'An litir ceart, san áit mícheart',
  WrongLetter: 'An litir mícheart',
  ProjectIsOpenSource: 'Tá an tionscnamh seo ar fáil ar fhoinse fhoscailte ar',
  PlayAgain: 'Imir Arís',
  CurrentStreak: 'Buanna gan stad',
  LongestStreak: 'An tsraith is faide buanna gan stad',
  Oops: 'Úps!',
  TheWordWas: 'Ba é an focal nó:',
  DarkMode: 'Mód dorcha',
  IfYouAreEnjoyingThisGame: 'Má tá tú ag baint suilt as an chluiche seo, tabhair tacaíocht domh trí',
  BuyMeACoffee: 'pionta Guinness a cheannacht domh',
  Enter: 'Tomhas',
}
