export const keyboardLetters = [
  ['A', 'Á', 'E', 'É', 'I', 'Í', 'O', 'Ó', 'U', 'Ú'],
  ['B', 'C', 'D', 'F', 'G', 'H', 'L', 'M', 'N'],
  ['P','R', 'S', 'T', 'V',],
]

export const letters = [
  'A',
  'Á',
  'B',
  'C',
  'D',
  'E',
  'É',
  'F',
  'G',
  'H',
  'I',
  'Í',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'Ó',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'Ú',
  'V',
  'X',
  'Y',
  'Z',
]

export const status = {
  green: 'green',
  yellow: 'yellow',
  gray: 'gray',
  unguessed: 'unguessed',
}

export const dictionary = {
  HowToPlay: 'Treoracha',
  SixGuessesLeft: 'Gheobhaidh tú 6 iarracht leis an fhocal cheart a thomhas.',
  GuessAnyValidWord: 'Glactar le mórchuid na bhfocal bailí Gaeilge. Ní ghlactar le hainmneacha dílse.',
  AfterEachGuessLetterWillTurnDifferentColour: 'I ndiaidh gach tomhas a dhéanann tú, cuirfear dath glas, buí nó liath ar na litreacha a chuir tú isteach.',
  CorrectLetterCorrectSpot: 'An litir ceart, san áit cheart',
  CorrectLetterWrongSpot: 'An litir ceart, san áit mícheart',
  WrongLetter: 'An litir mícheart',
  ProjectIsOpenSource: 'Tá an tionscnamh seo ar fáil ar fhoinse fhoscailte',
  PlayAgain: 'Imir Arís',
  CurrentStreak: 'Buanna gan briseadh',
  LongestStreak: 'Sraith is faide buanna gan briseadh',
  Oops: 'Úps!',
  TheWordWas: 'Ba é an focal nó:',
  DarkMode: 'Mód dorcha',
  IfYouAreEnjoyingThisGame: 'Má tá tú ag baint suilt as an chluiche seo, tabhair tacaíocht domh trí',
  BuyMeACoffee: 'phionta Guinness a cheannacht domh',
  Enter: 'Tomhas',
  ResultsCopiedToClipboard: 'Tá na torthaí cóipeáilte chuig an ghearrthaisce',
  ShareTheResults: 'Roinn na torthaí'
}
